export const INIT_RESTAURANTS = 'INIT_RESTAURANTS';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const SET_ERROR = 'SET_ERROR';
export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const GET_RESTAURANT_BY_ID = 'GET_RESTAURANT_BY_ID';
export const SET_CUISINE = 'SET_CUISINE';
export const SET_PRICE_RANGE = 'SET_PRICE_RANGE';
export const GET_RESTAURANT_DETAILS_BY_ID = 'GET_RESTAURANT_DETAILS_BY_ID';

export const ADD_USER = 'ADD_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
